# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macos-latest
    
    steps:
       - name: clone opcodeEmulator
         uses: actions/checkout@v3
         with:
           path: OpcodeEmulator
       
       - name: clone lilu
         uses: actions/checkout@v3
         with:
           repository: acidanthera/Lilu
           path: Lilu
           
       - name: clone MacKernelSDL
         uses: actions/checkout@v3
         with:
           repository: acidanthera/MacKernelSDK
           path: Lilu/MacKernelSDK
           
       - name: build lilu
         run: |
           xcodebuild -project ./Lilu/Lilu.xcodeproj -configuration Debug clean build ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES
      
       - name: build opcodeEmulator
         run: |
           cp -r ./Lilu/build/Debug/Lilu.kext ./OpcodeEmulator &&
           cp -Rf ./Lilu/MacKernelSDK ./OpcodeEmulator &&
           xcodebuild -project ./OpcodeEmulator/OpcodeEmulator.xcodeproj -configuration Release clean build ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES
           
       - uses: actions/upload-artifact@v3
         with:
           name: Package
           path: ./OpcodeEmulator/build
      
